export const metadata = {
  title: 'Chat',
  description: 'Generated by Next.js',
  icons: {
    icon: '/page.ico'
  }
}
// import QueryComponent from './components/QueryComponent';
import ReduxProvider from './components/ReduxProvider'
// Импорт Компонентов

import 'bootstrap/dist/css/bootstrap.min.css';
import '@/scss/main.scss'
import ClientBootstrap from './components/Bootstrap'


import Header from './components/Header'

// Импорт Шрифтов

import { Open_Sans } from 'next/font/google'

const sans = Open_Sans({
  subsets: ['latin'],
  weight: ['500']
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Header />
          <main>
            {children}          
          </main>
        </ReduxProvider>
      </body>
    </html>
  )
}
